swagger: '2.0'
info:
  title: API for Openshift.io health monitoring
  version: '0.1'
basePath: /api/v1/
consumes:
  - application/json
produces:
  - application/json
paths:
  /liveness:
    get:
      tags:
        - Service settings
      operationId: f8a_jobs.api_v1.get_liveness
      summary: Get job service liveness
      responses:
        '200':
          description: Service is alive
  /readiness:
    get:
      tags:
        - Service settings
      operationId: f8a_jobs.api_v1.get_readiness
      summary: Get job service readiness
      responses:
        '200':
          description: Service is ready
  '/reports':
    get:
      tags:
        - Healthcheck Services
      operationId: f8a_monitoring.api_v1.get_all_repo_report
      summary: Get healthcheck report for all registered repositories
      responses:
        '200':
          schema:
            items:
              $ref: "#/definitions/Report"
          description: Healthcheck data for all registered repositories
        '401':
          description: No suitable permissions
        '404':
          description: No image found
  '/reports/{name}':
    get:
      tags:
        - Healthcheck Services
      operationId: f8a_monitoring.api_v1.get_repo_report
      summary: Get healthcheck report for a registered repository
      parameters:
        - in: path
          name: name
          type: string
          required: true
          description: github repository name
      responses:
        '200':
          schema:
            $ref: "#/definitions/Report"
          description: Healthcheck report for given registered repository
        '401':
          description: No suitable permissions
        '404':
          description: No image found
  '/repos/register':
    post:
      tags:
        - Admin Services
      operationId: f8a_monitoring.api_v1.register_repo
      summary: Register a repository for monitoring
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: repo
          description: A registered repository
          required: true
          schema:
            $ref: '#/definitions/Repo'
      responses:
        '201':
          description: New repository registered
        '401':
          description: No suitable permissions
  '/repos/deregister':
    post:
      tags:
        - Admin Services
      operationId: f8a_monitoring.api_v1.deregister_repo
      summary: Deregister a monitored repository
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: repo
          description: A registered repository
          required: true
          schema:
            $ref: '#/definitions/Repo'
      responses:
        '200':
          description: Successfully deregistered the repository
        '401':
          description: No suitable permissions
        '404':
          description: No repository found
  '/repos/suspend':
    post:
      tags:
        - Admin Services
      operationId: f8a_monitoring.api_v1.suspend_repo
      summary: Suspend a monitored repository temporarily
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: repo
          description: A registered repository
          required: true
          schema:
            $ref: '#/definitions/Repo'
      responses:
        '200':
          description: Successfully deregistered the repository
        '401':
          description: No suitable permissions
        '404':
          description: No repository found
  '/repos/revive':
    post:
      tags:
        - Admin Services
      operationId: f8a_monitoring.api_v1.revive_repo
      summary: Revive a suspended repository for monitoring
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: repo
          description: A registered repository
          required: true
          schema:
            $ref: '#/definitions/Repo'
      responses:
        '200':
          description: Successfully deregistered the repository
        '401':
          description: No suitable permissions
        '404':
          description: No repository found
  '/scan':
    post:
      tags:
        - Healthcheck Services
      operationId: f8a_monitoring.api_v1.scan_repo
      summary: Scan registered repositories
      parameters:
        - in: body
          name: repos
          description: List of registered repositories. Wildcard character '*' is supported for all repositories.
          required: true
          schema:
            type: array
            items:
              $ref: '#/definitions/Repo'
      responses:
        '201':
          description: Started healthcheck for the given repository
        '401':
          description: No suitable permissions
        '404':
          description: No image found
definitions:
  Report:
    title: Healthcheck Report
    description: Healthcheck Report
    type: object
    properties:
      cve:
        type: array
        items:
          type: string
      license:
        type: array
        items:
          type: string
  Repo:
    title: Github Repository
    description: Github Repository
    properties:
      name:
        type: string

